import { StyleSheet } from "react-native";

import {
  CHILD_HEADING,
  CHILD_TEXT,
} from "@/src/theme/childTypography";

export const styles = StyleSheet.create({
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 72,
    gap: 14,
  },
  permissionsBlock: {
    borderRadius: 26,
    borderWidth: 2,
    padding: 16,
    gap: 4,
  },
  permissionsTitle: { ...CHILD_HEADING.h1, marginBottom: 4 },
  permissionsIntro: { ...CHILD_HEADING.h3, marginBottom: 8 },
  permissionsHint: { ...CHILD_TEXT.body, marginBottom: 12 },
  permissionDivider: {
    height: StyleSheet.hairlineWidth * 2,
    backgroundColor: "rgba(15, 23, 42, 0.08)",
    marginVertical: 14,
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rowIcon: {
    width: 56,
    height: 56,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTextWrap: { flex: 1, gap: 4 },
  cardTitle: { ...CHILD_HEADING.h2 },
  cardSubtitle: { ...CHILD_TEXT.body },
  statusBubble: {
    width: 48,
    height: 48,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  fixBtn: {
    minHeight: 54,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    marginTop: 12,
  },
  fixBtnPressed: { opacity: 0.9 },
  fixBtnDisabled: { opacity: 0.65 },
  fixBtnText: { color: "#FFFFFF", ...CHILD_HEADING.h3 },
  paletteHeaderRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  sectionTitle: { ...CHILD_HEADING.h2 },
  sectionHint: { ...CHILD_TEXT.body, marginTop: 4 },
  hueBarWrap: {
    marginTop: 10,
    width: "100%",
  },
  hueTrackOuter: {
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    overflow: "hidden",
    position: "relative",
    justifyContent: "center",
  },
  hueGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  hueThumb: {
    position: "absolute",
    top: "50%",
    marginTop: -13,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#FFFFFF",
    borderWidth: 3,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 3,
  },
  card: {
    borderRadius: 26,
    borderWidth: 2,
    padding: 16,
    gap: 14,
  },
  headerBackBtn: {
    marginLeft: 2,
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
});
